#!/usr/bin/env python3
""" Factor numbers """
from sys import argv
from math import sqrt


def factorize(n):
	sqrt_n = int(n**0.5)
	for candidate in range(2, sqrt_n + 1):
		if n % candidate == 0:
			return candidate, n // candidate
		return n, 1

def main(filename):
	with open(filename, 'r') as file:
		for line in file:
			num = int(line.strip())
			factor1, factor2 = factorize(num)
			print(f"{num}={factor1}*{factor2}")

if __name__ == "__main__":
	if len(sys.argv) != 2:
		print("Usage: factors <file>")
		sys.exit(1)

	filename = sys.argv[1]
	main(filename)
