#!/usr/bin/env python3
"""Factor numbers"""
from sys import argv
from math import sqrt


def is_prime(num):
	"""Check if a number is prime."""
	if num < 2:
		return False
	for i in range(2, int(math.sqrt(num)) + 1):
		if num % i == 0:
			return False
	return True

def factorize_rsa_number(n):
	""Factorize an RSA number into the product of two prime numbers"""
	for i in range(2, n):
		if n % i == 0 and is_prime(i) and is_prime(n // i):
			return i, n // i

def main(filename):
	"""Read RSA numbes from file and factorize each one"""
	with open(filename, 'r') as file:
		for line in file:
			num = int(line.strip())
			factor1, factor2 = factorize_rsa_number(num)
			print(f"{num}={factor1}*{factor2}")

if __name__ == "__main__":
	if len(sys.argv) != 2:
		print("Usage: rsa <file>")
		sys.exit(1)

	filename = sys.argv[1]
	main(filename)
